package proyectofinal;
import Conexion.Conex;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 177771
 */
public class InterfazModificarPerfil extends javax.swing.JFrame {
    InterfazLogIn IL = new InterfazLogIn();
    public InterfazModificarPerfil() {
        initComponents();
        System.out.println(IL.Usuarioe);
        System.out.println(IL.Contrae);
        
        try {
            Connection con;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:4306/groovemusic","root","");
            Statement st;
            ResultSet rs;           
            st=con.createStatement();
            rs=st.executeQuery("select * from clientes WHERE NomUsu='"+IL.Usuarioe+"' AND Password='"+IL.Contrae+"';");
            while (rs.next()) {                  
                lblVnom.setText(rs.getString("NombreCli"));
                lblVap.setText(rs.getString("ApellidosCli"));
                lblVnu.setText(rs.getString("NomUsu"));
                lblVrfc.setText(rs.getString("RFC"));
                lblVce.setText(rs.getString("CorreoEle"));
                lblVpass.setText(rs.getString("Password"));   
            }
            con.close();
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
        
                        
        cbDatMod.addItem("Nombre");
        cbDatMod.addItem("Apellidos");    
        cbDatMod.addItem("Nombre de usuario");
        cbDatMod.addItem("RFC");   
        cbDatMod.addItem("Correo Electronico");
        cbDatMod.addItem("Contraseña");   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModPerf = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblAp = new javax.swing.JLabel();
        lblNU = new javax.swing.JLabel();
        lblCoEl = new javax.swing.JLabel();
        lblContr = new javax.swing.JLabel();
        lblRFC = new javax.swing.JLabel();
        btnBackMenu = new javax.swing.JButton();
        lblVnom = new javax.swing.JLabel();
        lblVap = new javax.swing.JLabel();
        lblVnu = new javax.swing.JLabel();
        lblVrfc = new javax.swing.JLabel();
        lblVce = new javax.swing.JLabel();
        lblVpass = new javax.swing.JLabel();
        cbDatMod = new javax.swing.JComboBox<>();
        lblDatMod = new javax.swing.JLabel();
        tfValMod = new javax.swing.JTextField();
        lblEscMod = new javax.swing.JLabel();
        btnMod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblModPerf.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblModPerf.setText("Modificar Perfil");

        lblNom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNom.setText("Nombre: ");

        lblAp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAp.setText("Apellidos: ");

        lblNU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNU.setText("Nombre de Usuario: ");

        lblCoEl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCoEl.setText("Correo Electronico: ");

        lblContr.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblContr.setText("Contraseña:");

        lblRFC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRFC.setText("RFC: ");

        btnBackMenu.setText("Regresar al menu");
        btnBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMenuActionPerformed(evt);
            }
        });

        lblVnom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVnom.setText("txtNom");

        lblVap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVap.setText("txtAp");

        lblVnu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVnu.setText("txtNU");

        lblVrfc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVrfc.setText("txtRFC");

        lblVce.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVce.setText("txtCorreo");

        lblVpass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVpass.setText("txtContra");

        cbDatMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDatModActionPerformed(evt);
            }
        });

        lblDatMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDatMod.setText("Dato a modificar: ");

        lblEscMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEscMod.setText("Escribe la modificación: ");

        btnMod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(lblModPerf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(btnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNom)
                            .addComponent(lblAp))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVap)
                            .addComponent(lblVnom))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblContr)
                                .addGap(43, 43, 43)
                                .addComponent(lblVpass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCoEl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblVce))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNU)
                                        .addGap(36, 36, 36)
                                        .addComponent(lblVnu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRFC)
                                        .addGap(53, 53, 53)
                                        .addComponent(lblVrfc)))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(lblEscMod)
                        .addGap(18, 18, 18)
                        .addComponent(tfValMod, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDatMod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbDatMod, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModPerf)
                            .addComponent(btnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNom)
                            .addComponent(lblVnom))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAp)
                            .addComponent(lblVap)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDatMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatMod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEscMod)
                            .addComponent(tfValMod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNU)
                            .addComponent(lblVnu))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRFC)
                            .addComponent(lblVrfc))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVce)
                            .addComponent(lblCoEl))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContr)
                            .addComponent(lblVpass))))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMenuActionPerformed
        MenuOpcionesVentas bmv= new MenuOpcionesVentas();
        bmv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackMenuActionPerformed

    private void cbDatModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDatModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDatModActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        int DM=cbDatMod.getSelectedIndex();
        String tVM = tfValMod.getText();
        
        try {
            Connection con;
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:4306/groovemusic","root","");
            Statement st;
            st=con.createStatement();

            if (DM==0) {
                st.executeUpdate("UPDATE clientes SET NombreCli='"+tVM+"' WHERE NomUsu='"+IL.Usuarioe+"' AND Password='"+IL.Contrae+"';");
            }
            if (DM==1) {
                st.executeUpdate("UPDATE clientes SET ApellidosCli='"+tVM+"' WHERE NomUsu='"+IL.Usuarioe+"' AND Password='"+IL.Contrae+"';");
            }
            if (DM==2) {
                st.executeUpdate("UPDATE clientes SET NomUsu='"+tVM+"' WHERE NomUsu='"+IL.Usuarioe+"' AND Password='"+IL.Contrae+"';");
                JOptionPane.showMessageDialog(null,"Se cerrará sesión para aplicar los cambios","ALERTA",JOptionPane.INFORMATION_MESSAGE);  
                InterfazLogIn l= new InterfazLogIn();
                l.setVisible(true);
                this.dispose();
            }
            if (DM==3) {
                st.executeUpdate("UPDATE clientes SET RFC='"+tVM+"' WHERE NomUsu='"+IL.Usuarioe+"' AND Password='"+IL.Contrae+"';");
            }
            if (DM==4) {
                st.executeUpdate("UPDATE clientes SET CorreoEle='"+tVM+"' WHERE NomUsu='"+IL.Usuarioe+"' AND Password='"+IL.Contrae+"';");
            }
            if (DM==5) {
                st.executeUpdate("UPDATE clientes SET Password='"+tVM+"' WHERE NomUsu='"+IL.Usuarioe+"' AND Password='"+IL.Contrae+"';");
                JOptionPane.showMessageDialog(null,"Se cerrará sesión para aplicar los cambios","ALERTA",JOptionPane.INFORMATION_MESSAGE);  
                InterfazLogIn l= new InterfazLogIn();
                l.setVisible(true);
                this.dispose();
            }

            con.close();
            
            
        } catch (Exception e) {
            System.out.println("Error: "+e);
        }
        
    }//GEN-LAST:event_btnModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazModificarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMenu;
    private javax.swing.JButton btnMod;
    private javax.swing.JComboBox<String> cbDatMod;
    private javax.swing.JLabel lblAp;
    private javax.swing.JLabel lblCoEl;
    private javax.swing.JLabel lblContr;
    private javax.swing.JLabel lblDatMod;
    private javax.swing.JLabel lblEscMod;
    private javax.swing.JLabel lblModPerf;
    private javax.swing.JLabel lblNU;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblRFC;
    private javax.swing.JLabel lblVap;
    private javax.swing.JLabel lblVce;
    private javax.swing.JLabel lblVnom;
    private javax.swing.JLabel lblVnu;
    private javax.swing.JLabel lblVpass;
    private javax.swing.JLabel lblVrfc;
    private javax.swing.JTextField tfValMod;
    // End of variables declaration//GEN-END:variables
}
